[package]
name = "portable-shortcuts"
version = "0.1.0"
authors = ["daniel"]

[dependencies]
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"

[build-dependencies]
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"

